# Generated by Django 2.2.4 on 2019-09-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram',
            old_name='nama_belakang',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='instagram',
            old_name='nama_depan',
            new_name='last_name',
        ),
    ]
